aubo_i5:
  # publish all joint states--------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Gazebo use controller that ros_control(joint_position_controller)
  # Position Controllers------------------
  shoulder_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 0.0,  i: 0.0, d: 0.0, i_clamp: 1}

  upperArm_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: upperArm_joint
    pid: {p: 0.0,  i: 0.00, d: 0.0, i_clamp: 1}

  foreArm_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: foreArm_joint
    pid: {p: 0.0,  i: 0.0, d: 0.0, i_clamp: 1}

  wrist1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist1_joint
    pid: {p: 0.0,  i: 0.00, d: 0.0, i_clamp: 1}

  wrist2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist2_joint
    pid: {p: 0.0,  i: 0.00, d: 0.0, i_clamp: 1}

  wrist3_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist3_joint
    pid: {p: 0.0,  i: 0.00, d: 0.0, i_clamp: 1}

