# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

joint_limits:
  arm_mount_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 2
  foreArm_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.7
  shoulder_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.7
  upperArm_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.7
  wrist1_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
  wrist2_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
  wrist3_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
